### ISSUE TITLE
Scala for Java Importing Error

### ISSUE THREAD

**Issue by widian** [originell/jpype#159]
I want to use some Jar file which is using Scala for Java packages, for instance scala.collection

But in progress of making _JavaClass, JPype1 raises below error.

TypeError: Cannot create a consistent method resolution
order (MRO) for bases scala.collection.GenTraversableLike$$Static, scala.collection.generic.HasNewBuilder$$Static

Maybe, I think it is conflict in inheritance definition. I try to avoid that case to modify a JPype1, but I couldn't. Anyone who can avoid this situation? 

These are used Scala for Java packages.

import scala.collection.Iterator;
import scala.collection.JavaConversions;
import scala.collection.Seq;

**Comment by marcoeilers** [comment]
I had the same problem; I think the issue seems to be the following: 

JPype translates all Java types, both classes and interfaces, to Python types. That means that in complex subtyping hierarchies for interfaces, which may include diamonds and (importantly) the same parent interfaces several times in different orders for a given type, Python may not be able to find a consistent MRO. I think this is a general issue and has nothing to do with Scala, except that Scala has such complex hierarchies in commonly used types.

One solution I could think of is this: When computing the bases and meta bases for a new type, the base interfaces, whose order does not matter because they don't contain any actual method implementations, could be sorted (e.g. by name). This should not affect execution at all, but solves the problem of potentially having the same interfaces in different orders in a type's inheritance hierarchy.

I changed _jclass.py to include this code:

        # Prepare the meta-metaclass
        meta_bases = []
        def getMetaClass(base):
            if base is object:
                return cls
            else:
                return base.__metaclass__
        for i in bases:
            meta_bases.append(getMetaClass(i))

        minterfaces = []
        mclasses = []
        for mb in meta_bases:
            if hasattr(mb, '__isinterface__') and mb.__isinterface__:
                minterfaces.append(mb)
            else:
                mclasses.append(mb)
        def getName(metaclass):
            return metaclass.__name__
        minterfaces = sorted(minterfaces, key=getName)
        
        meta_bases = mclasses + minterfaces

        interfaces = []
        classes = []
        for b in bases:
            mb = getMetaClass(b)
            if hasattr(mb, 'isinterface') and mb.__isinterface__:
                interfaces.append(b)
            else:
                classes.append(b)
        def getBaseName(base):
            return getName(getMetaClass(base))

        interfaces = sorted(interfaces, key=getBaseName)

        bases = classes + interfaces     
        static_fields["isinterface"] = jc.isInterface()


This solves the immediate problem for me, but as you can see, it is 
a) not coded very nicely (I am not a Python programmer at all and I just needed to get things to work, don't judge)
b) probably not going to work with Java 8 interfaces that contain default implementations.

If someone has a nicer and/or general solution, or knows a case where this one doesn't work except for default implementations in interfaces, I'd be glad to hear about it.

**Comment by widian** [comment]
Unfortunately, it didn't work on my environment. In fact, my JPype environment built on Java 8 interfaces, but I couldn't certainly identify that the reason of not working is cause of Java 8 interface.

I replace a JPype code from meta_bases to before metaclass definition. But Jpype executed same error in my case. Maybe I need to change my Java interfaces.

**Comment by widian** [comment]
Thank you for your contribution and I checked this issue has solved. If there is no more issues, I will close this issue. Once more, thank you!
