### ISSUE TITLE
jpype & KeyboardInterrupt

### ISSUE THREAD

**Issue by bartoszbielawski** [originell/jpype#255]
Hi,

I'm using jpype to call some Java stuff from my Python scripts. I have a try..exception..finally block that tries to do some kind of clean-up when the script is interrupted by ^C. 

It seems that after I start JVM from jpype (jpype.startJVM()) the signal handler doesn't send KeyboardInterrupt and the script dies immediately without doing any clean-up. 

Here's a sample code we used to trigger the problem:
https://gist.github.com/bartoszbielawski/a92801856ad2eb57dbfadd993cd5f601
If the signal handler is not installed you can see how the script terminates abruptly. 

System parameters:
-CentOS 7 (64b)
-Python 3.6.0 from Anaconda 4.3.0
-jpype 0.6.2
-Java "1.8.0_121"

Could this be a bug in jpype or is it deeper?

Cheers,
Bartosz

**Comment by jaseg** [comment]
This is a side effect of the JVM registering its own signal handlers. You can prevent that by passing ```-Xrs``` to ```startJVM```, thereby telling the JVM to not register its shutdown signal handlers.

Note that this will only allow python to handle the signal when you're back in python land from Java. If you're e.g. in the middle of a ```java.lang.Thread.sleep(1000000)```, that will still block because then python is handling the signal and doesn't know how to tell java to cut it out.

**Comment by bartoszbielawski** [comment]
I see, thanks. In my case Java and Python code is interleaved so we can accept a delay of few seconds. Thanks again :)
