### ISSUE TITLE
Unable to set classpath 

### ISSUE THREAD

**Issue by muh182** [originell/jpype#283]
I am trying to call java classes in Python using jpype. I can call Java libraries such as `java.lang.system.out.println()`. However, when I try to access the java code I have developed, it fails. I have my `.class` files in `demo` directory at the same level as `testJpype.py`.

__testJpype.py__
```
from jpype import *
import sys,os,os.path,glob

root = os.path.abspath(os.path.dirname(__file__))
startJVM("/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre/lib/jli/libjli.dylib",
               "-Djava.class.path=%s%sdemo" % (root, os.sep))
print( "-Djava.class.path=%s%sdemo" % (root, os.sep))

java.lang.System.out.println("Hello World")

testPkg = JPackage('demo')
Test = testPkg.Apple()
```

__Apple.java__ is as simple as:
```
package demo;
public class Apple {
    
    public Apple () {
        super();
        System.out.println("**************Test**********");
    }
}
```

The error message is:
```
-Djava.class.path=/Users/mo/Desktop/jython/src/demo/demo
Hello World
Traceback (most recent call last):
  File "testJpype.py", line 12, in <module>
    Test = testPkg.Apple()
  File "/Library/Python/2.7/site-packages/jpype/_jpackage.py", line 60, in __call__
    raise TypeError("Package {0} is not Callable".format(self.__name))
TypeError: Package demo.Apple is not Callable
```

**Comment by marscher** [comment]
There are no mistakes in your script. Can you call your demo class from java itself?

**Comment by Thrameos** [comment]
This was the standard behavior before the use of jpype.imports module.  If the class can not be loaded for any reason the JPackage just assumes that any objects in the package are another package.  The likely causes of this are:

1) The class path is incorrect or the jar is not in the class path.
2) The jar is incompatible with the jvm (such as Java 1.8 jar and a 1.6 jvm)
3) A jar dependency is missing or incompatible.
4) A jar depends on a jni shared library file that is missing or incompatible.

I would suggest starting by placing the full path including the jar name as the classpath.  The requirements for classpaths when called from the jni are different than when calling java at the command line.  Things like wildcards do not work.  It is usually safest to specify the full jar.  We have a classpath utility that can take a classpath with wildcards and enumerate out the jars.  Last use jpype.imports rather than JPackage as that will produce more meaningful errors on a failure.  

Thia also reminds me we may want to try to get the ignore unrecognized in.  Another silent failure is a typo in the -Djava.class.path that results in it not be interpreted.  I don't see any problems here, but others have hit it.

**Comment by muh182** [comment]
Thanks that helps. The error is fixed.

A follow up question is how to to create this using Jpype:`java.util.Date("2016-02-16 04:00:00")`?

I get this error:

```
Traceback (most recent call last):
 File "kmeansConsumption-Temperature.py", line 52, in <module>
   java.util.Date("2016-02-16 04:00:00")
 File "/sw/lib/python2.7/site-packages/jpype/_jclass.py", line 86, in _javaInit
   *args)
jpype._jexception.IllegalArgumentExceptionPyRaisable: java.lang.IllegalArgumentException
```

**Comment by marscher** [comment]
http://lmgtfy.com/?q=java+util+data+illegalargumentexception
